# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedler', '0003_entry_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='lang',
            field=models.CharField(blank=True, choices=[('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('en', 'English'), ('', ' * * * ')], default='', max_length=2),
        ),
    ]
