# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedler', '0004_auto_20170905_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedler.Stream', verbose_name='Original stream'),
        ),
    ]
