# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedler', '0006_auto_20171012_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedlysettings',
            old_name='feedly_stream',
            new_name='streams',
        ),
        migrations.RemoveField(
            model_name='feedlysettings',
            name='feedly_auth',
        ),
        migrations.RemoveField(
            model_name='feedlysettings',
            name='feedly_pages',
        ),
        migrations.AddField(
            model_name='feedlysettings',
            name='token',
            field=models.CharField(blank=True, help_text='Access Token from developer.feedly.com', max_length=255),
        ),
    ]
