# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedler', '0006_auto_20171012_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedlysettings',
            old_name='feedly_stream',
            new_name='streams',
        ),
        migrations.RemoveField(
            model_name='feedlysettings',
            name='feedly_auth',
        ),
        migrations.RemoveField(
            model_name='feedlysettings',
            name='feedly_pages',
        ),
        migrations.AddField(
            model_name='feedlysettings',
            name='refresh',
            field=models.CharField(blank=True, help_text='Refresh Token for automatic update (pro account)', max_length=1024),
        ),
        migrations.AddField(
            model_name='feedlysettings',
            name='token',
            field=models.CharField(blank=True, help_text='Access Token from feedly.com/v3/auth/dev', max_length=1024),
        ),
        migrations.AlterField(
            model_name='stream',
            name='ident',
            field=models.CharField(help_text='Example: enterprise/myuser/tag/abcd...', max_length=255),
        ),
    ]
