# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedler', '0007_auto_20171016_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='visual',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
