# Generated by Django 3.2.13 on 2022-05-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedler', '0008_auto_20171117_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time'),
        ),
    ]
