---
- name: remove deprecated or insecure packages | package-01 - package-09
  apt:
    name: '{{ item }}'
    state: 'absent'
  with_items:
    - '{{ os_security_packages_list }}'
  when: 'os_security_packages_clean'
