---
- name: (Alpine Linux) Configure NGINX repository
  lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ nginx_repository | default(nginx_default_repository_alpine) }}"

- name: (Alpine Linux) Install NGINX
  apk:
    name: "nginx{{ nginx_version | default('') }}"
    repository: "{{ nginx_repository | default(nginx_default_repository_alpine) }}"
    state: "{{ nginx_state }}"
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX
