---
- name: (Debian/Ubuntu) Configure NGINX repository
  apt_repository:
    filename: nginx
    repo: "{{ item }}"
    update_cache: yes
    mode: 0644
  loop: "{{ nginx_repository | default(nginx_default_repository_debian) }}"

- name: (Debian/Ubuntu) Install NGINX
  apt:
    name: "nginx{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX
