---
- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) {{ nginx_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  yum_repository:
    name: nginx-plus
    baseurl: "{{ nginx_repository |
              default(lookup('vars', 'nginx_plus_default_repository_' + ((ansible_facts['distribution'] == 'Amazon') | ternary('amazon', 'redhat')))) }}"
    description: NGINX Plus Repository
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: yes
    gpgcheck: yes
    state: "{{ nginx_license_status | default ('present') }}"
    mode: 0644

- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) Install NGINX Plus
  yum:
    name: "nginx-plus{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_license_status is not defined
  notify: (Handler) Run NGINX
