---
- name: (SLES) Combine NGINX Plus certificate and license key
  assemble:
    src: /etc/ssl/nginx
    dest: /etc/ssl/nginx/nginx-repo-bundle.crt
    mode: 0444
  when: nginx_license_status is not defined

- name: (SLES) {{ nginx_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  zypper_repository:
    name: nginx-plus
    repo: "{{ nginx_repository | default(nginx_plus_default_repository_suse) }}"
    state: "{{ nginx_license_status | default ('present') }}"

- name: (SLES) Install NGINX Plus
  zypper:
    name: "nginx-plus{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_license_status is not defined
  notify: (Handler) Run NGINX
