---
- name: Set NGINX Plus license state to absent
  set_fact:
    nginx_license_status: absent

- name: (Debian/Red Hat/SLES OSs) Delete NGINX Plus license
  file:
    path: /etc/ssl/nginx
    state: absent
  when: ansible_facts['distribution'] != "Alpine"

- name: (Alpine Linux) Delete NGINX Plus license
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apk/cert.key
    - /etc/apk/cert.pem
  when: ansible_facts['distribution'] == "Alpine"

- name: Remove NGINX Plus repository data
  include_tasks: "{{ role_path }}/tasks/plus/install-{{ ansible_facts['os_family'] | lower }}.yml"
