---
- name: "(Install: Debian/Ubuntu) Add NGINX Unit Repository"
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - deb [arch=amd64] https://packages.nginx.org/unit/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} unit
    - deb-src [arch=amd64] https://packages.nginx.org/unit/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} unit
