---

django_project_name: publichealth

elasticsearch_heap_size: 1g

memcached_memory_allocation_mb: 256

nginx_worker_processes: 2
nginx_worker_connections: 1024

domain: "{{ vault_domain }}"

django_email_key: "{{ vault_django_email_key }}"
django_email_domain: "{{ vault_django_email_domain }}"
django_email_from: "{{ vault_django_email_from }}"

django_secret_key: "{{ vault_django_secret_key }}"

# Default: postgres://postgres:@postgres:5432/postgres
django_postgres_url: "{{ vault_django_postgres_url }}"
