---

- name: Create release directory
  file: path={{ release_dir }} state=directory owner=ansible group=ansible
  become: true

- name: Checkout code branch from git
  git:
    dest: "{{ release_dir }}"
    repo: "{{ gitrepo }}"
    version: "{{ gitversion }}"
    force: false

- name: Copy Docker site configuration
  template:
    src: docker-compose.j2
    dest: "{{ release_dir }}/docker-compose.yml"

- name: Ensure Make is installed
  become: true
  apt:
    pkg: make

- name: Deploy Wagtail site on Docker
  shell: make build-cached
  args:
    chdir: "{{ release_dir }}"

- name: Start Wagtail site
  shell: make run
  args:
    chdir: "{{ release_dir }}"


- name: Finish setup of Wagtail site
  shell: make setup
  args:
    chdir: "{{ release_dir }}"

- name: Finish setup of Wagtail site
  shell: make setup EMAIL={{ email_admin }}
  args:
    chdir: "{{ release_dir }}"
