---

- name: Checkout code branch from git
  git:
    dest: "{{ release_dir }}"
    repo: "{{ gitrepo }}"
    version: "{{ gitversion }}"
    force: no

- name: Copy Docker site configuration
  template:
    src: docker-compose.j2
    dest: "{{ release_dir }}/docker-compose.yml"

- name: Update Docker site
  debug:
    msg: "Please run 'make release' in {{ release_dir }} to finish updating the site"
