---

- name: Checkout code branch from git
  git:
    dest: "{{ release_dir }}"
    repo: "{{ gitrepo }}"
    version: "{{ gitversion }}"
    force: no

- name: Copy Docker site configuration
  template:
    src: docker-compose.j2
    dest: "{{ release_dir }}/docker-compose.yml"

- name: Rebuild and release Wagtail site
  shell: make release
  args:
    chdir: "{{ release_dir }}"
