---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-nginx
  vars:
    nginx_debug_output: true

    nginx_install_from: source
    nginx_branch: mainline
    nginx_install_source_build_tools: true
    nginx_install_source_pcre: false
    nginx_install_source_openssl: true
    nginx_install_source_zlib: false

    nginx_main_upload_enable: true
    nginx_main_upload_src: files/nginx.conf
    nginx_http_upload_enable: true
    nginx_http_upload_src: files/http/*.conf
