---
- name: (Amazon Linux/CentOS/RHEL) Add NGINX Amplify agent repository
  yum_repository:
    name: nginx-amplify
    baseurl: http://packages.amplify.nginx.com/{{ (ansible_facts['distribution'] == "Amazon") | ternary('amzn/', 'centos/') }}/$releasever/$basearch/
    description: NGINX Amplify Agent
    enabled: yes
    gpgcheck: yes
    mode: 0644
