---
- name: "(Install: Debian/Ubuntu) Add NGINX Amplify Agent Repository"
  apt_repository:
    filename: nginx-amplify
    repo: deb [arch=amd64] http://packages.amplify.nginx.com/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} amplify-agent
