---

- name: Create release directory
  file: path={{ release_dir }} state=directory owner=ansible group=ansible
  become: true

- name: Checkout code branch from git
  git:
    repo: 'https://github.com/datalets/public-health-ch'
    dest: "{{ release_dir }}"
    force: yes

- name: Copy Docker site configuration
  template:
    src: docker-compose.j2
    dest: "{{ release_dir }}/docker-compose.yml"

- name: Deploy Docker site
  shell: make setup
  args:
    chdir: "{{ release_dir }}"
