---

- name: Checkout code branch from git
  git:
    repo: 'https://github.com/datalets/public-health-ch'
    dest: "{{ release_dir }}"
    force: yes
    version: "{{ gitversion }}"

- name: Copy Docker site configuration
  template:
    src: docker-compose.j2
    dest: "{{ release_dir }}/docker-compose.yml"

- name: Update Docker site
  debug:
    msg: "Please run 'make release' in {{ release_dir }} to finish updating the site"
