- hosts: webservers
  become: false
  gather_facts: True
  vars:
    release_dir: /opt/publichealth
    archive_dir: /opt/www-old
    django_log_dir: /var/log/publichealth
    ipv4_addresses: "{{ ansible_all_ipv4_addresses }}"
  environment:
    COMPOSE_FILE: "{{ release_dir }}/docker-compose.yml"
    COMPOSE_PROJECT_NAME: publichealth
  roles:
    - web
