- hosts: webservers
  become: false
  gather_facts: true
  vars:
    gitrepo: https://github.com/datalets/public-health-ch
    gitversion: master
    release_dir: /opt/publichealth
    archive_dir: /opt/www-old
    django_log_dir: /var/log/publichealth
    redis_data_dir: /opt/redis/data
    ipv4_addresses: "{{ ansible_all_ipv4_addresses }}"
  environment:
    COMPOSE_FILE: "{{ release_dir }}/docker-compose.yml"
    COMPOSE_PROJECT_NAME: publichealth
  roles:
    - wagtail
