# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contact_contact_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataletssettings',
            options={'verbose_name': 'Get support'},
        ),
    ]
