# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170920_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataletssettings',
            options={'verbose_name': 'Datalets'},
        ),
        migrations.AlterField(
            model_name='dataletssettings',
            name='feedback_comment',
            field=models.TextField(blank=True, help_text='Any questions or general feedback', verbose_name='Comments..'),
        ),
        migrations.AlterField(
            model_name='dataletssettings',
            name='feedback_question',
            field=models.TextField(blank=True, help_text='Who should we reply to for questions?', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dataletssettings',
            name='feedback_status',
            field=models.IntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], help_text='How are you enjoying Wagtail?', null=True, verbose_name='Rating'),
        ),
    ]
