# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20171013_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articleindexpage',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_en',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.RichTextBlock()), ('section', wagtail.core.blocks.CharBlock(classname='full title')), ('info', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('summary', wagtail.core.blocks.RichTextBlock(required=True)), ('action', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))), icon='help')), ('media', wagtail.core.blocks.ChoiceBlock(choices=[('gallery', 'Image gallery')], icon='media'))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='infos_en',
            field=wagtail.core.fields.StreamField((('info', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('summary', wagtail.core.blocks.RichTextBlock(required=True)), ('action', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
