# Generated by Django 3.0.14 on 2021-09-28 16:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_contactformfield_clean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='subscribe_label_de',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articleindexpage',
            name='subscribe_label_en',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articleindexpage',
            name='subscribe_label_fr',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
