# Generated by Django 3.0.14 on 2021-09-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210928_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='subscribe_action',
            field=models.URLField(blank=True, default=''),
        ),
    ]
