# Generated by Django 3.0.14 on 2021-09-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_articleindexpage_subscribe_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpage',
            name='subscribe_action',
            field=models.URLField(blank=True, default='', verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='articleindexpage',
            name='subscribe_label_de',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Button Label (de)'),
        ),
        migrations.AlterField(
            model_name='articleindexpage',
            name='subscribe_label_en',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Button Label (en)'),
        ),
        migrations.AlterField(
            model_name='articleindexpage',
            name='subscribe_label_fr',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Button Label (fr)'),
        ),
    ]
