# Generated by Django 3.2.11 on 2022-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210928_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='news_letter_text',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='contact',
            name='news_letter_text_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='news_letter_text_fr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='news_letter_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
