---

galaxy_info:
  author: Oleg Lavrovsky
  description: Install Wagtail on Ubuntu with docker-compose
  license: MIT
  min_ansible_version: 1.2
  github_branch: master

  platforms:
  - name: Ubuntu
    versions:
    - all

  galaxy_tags:
  - docker
  - wagtail

dependencies: []
