---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --force-color
platforms:
  - name: alpine-3.10
    image: alpine:3.10
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
  - name: alpine-3.11
    image: alpine:3.11
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
  - name: alpine-3.12
    image: alpine:3.12
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
provisioner:
  name: ansible
  playbooks:
    converge: ../common/playbooks/source_converge.yml
    verify: ../common/playbooks/source_verify.yml
